In [4]:
import numpy as np
five_store = np.random.randint(100,10000,size=(5,30))
five_store_cumsum = five_store.cumsum(axis=1)
five_store_cumsum

array([[  1278,  11176,  12791,  17798,  25684,  28534,  32157,  33012,
         41452,  51134,  53290,  55172,  59335,  65915,  75499,  81923,
         86235,  88190,  94285,  95917, 100324, 100692, 109919, 117612,
        125214, 129753, 137207, 137912, 139935, 148115],
       [  7334,  11167,  18020,  18128,  18484,  24509,  28510,  37780,
         41211,  46327,  52627,  61087,  67634,  72503,  81824,  86938,
         92923, 102276, 106276, 108701, 115119, 118435, 123857, 129860,
        138413, 139324, 143004, 152705, 152805, 158197],
       [  1993,  11033,  15149,  21798,  24301,  27506,  31479,  32960,
         33967,  38184,  38530,  48388,  53863,  60744,  64986,  71184,
         80808,  90494,  90707,  94851,  97038, 104275, 110563, 116033,
        118853, 125103, 128820, 129175, 134361, 134493],
       [  9561,  18017,  20409,  27643,  29802,  39499,  49385,  51454,
         59761,  68649,  70215,  71928,  76670,  81295,  89449,  90606,
         93471,  98950, 103521, 105757, 106500, 111297, 116138, 124156,
        126743, 136703, 142829, 146627, 151973, 153221],
       [  6341,   7433,   9853,  14167,  17643,  20145,  23342,  31477,
         33806,  42651,  49312,  52481,  58776,  64199,  70402,  75353,
         82407,  89157,  95866, 104967, 108317, 116719, 118148, 122067,
        131756, 137579, 145839, 147263, 153517, 156970]])

In [ ]:
import pandas as pd

#.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)
five_store = pd.DataFrame(five_store_cumsum,
                          columns=[f'第{day}天' for day in range(1,31)],
                          index=["台北分店","新竹分店",'台中分店','台南分店','高雄分店'])

#.T = Chuyển đổi (transpose) DataFrame: hàng thành cột, cột thành hàng
new_df = five_store.T
new_df

        台北分店    新竹分店    台中分店    台南分店    高雄分店
第1天     1278    7334    1993    9561    6341
第2天    11176   11167   11033   18017    7433
第3天    12791   18020   15149   20409    9853
第4天    17798   18128   21798   27643   14167
第5天    25684   18484   24301   29802   17643
第6天    28534   24509   27506   39499   20145
第7天    32157   28510   31479   49385   23342
第8天    33012   37780   32960   51454   31477
第9天    41452   41211   33967   59761   33806
第10天   51134   46327   38184   68649   42651
第11天   53290   52627   38530   70215   49312
第12天   55172   61087   48388   71928   52481
第13天   59335   67634   53863   76670   58776
第14天   65915   72503   60744   81295   64199
第15天   75499   81824   64986   89449   70402
第16天   81923   86938   71184   90606   75353
第17天   86235   92923   80808   93471   82407
第18天   88190  102276   90494   98950   89157
第19天   94285  106276   90707  103521   95866
第20天   95917  108701   94851  105757  104967
第21天  100324  115119   97038  106500  108317
第22天  100692  118435  104275  111297  116719
第23天  109919  123857  110563  116138  118148
第24天  117612  129860  116033  124156  122067
第25天  125214  138413  118853  126743  131756
第26天  129753  139324  125103  136703  137579
第27天  137207  143004  128820  142829  145839
第28天  137912  152705  129175  146627  147263
第29天  139935  152805  134361  151973  153517
第30天  148115  158197  134493  153221  156970

In [14]:
#Trả về dữ liệu của cột "台中分店"
new_df['台中分店']

第1天       1993
第2天      11033
第3天      15149
第4天      21798
第5天      24301
第6天      27506
第7天      31479
第8天      32960
第9天      33967
第10天     38184
第11天     38530
第12天     48388
第13天     53863
第14天     60744
第15天     64986
第16天     71184
第17天     80808
第18天     90494
第19天     90707
第20天     94851
第21天     97038
第22天    104275
第23天    110563
第24天    116033
第25天    118853
第26天    125103
第27天    128820
第28天    129175
第29天    134361
第30天    134493
Name: 台中分店, dtype: int64