In [24]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,index=range(1, 51),columns=['國文', '英文', '數學', '地理', '歷史'])
scores_df.index.name = "學號"
scores_df.columns.name = "科目"

In [25]:
scores_df1 = scores_df.copy()

In [ ]:
def cal1(s):
    return s.sum()
scores_df.apply(cal1,axis=1)

In [26]:
def cal2(s):
    nums = int(s[s<60].count())
    return nums
scores_df1['不及格的科目'] = scores_df.apply(cal2,axis=1)
scores_df1

科目   國文  英文   數學  地理   歷史  不及格的科目
學號
1    90  53   97  67   86       1
2    67  69   64  89   86       0
3    50  99   97  88   92       1
4    67  55   78  56   55       3
5    60  97   68  89  100       0
6    63  96   90  81   76       0
7    97  80  100  89   83       0
8    99  72   53  92   56       2
9    58  59   93  54   54       4
10   63  58   87  65   51       2
11   55  98   95  93   52       2
12   60  95   99  95   75       0
13   63  82   81  91   60       0
14   90  54   59  89   92       2
15   97  69  100  88   90       0
16   98  75   95  94   97       0
17   70  97   58  99   54       2
18   79  88   75  89  100       0
19   89  87   95  56   78       1
20   76  78   93  60   57       1
21   53  58   95  57   62       3
22   71  73   66  54   64       1
23   82  63   79  91   60       0
24   50  81   61  67   86       1
25  100  69   66  65   96       0
26   95  58   71  96   69       1
27   79  68   81  93   63       0
28   93  90   73  87   83       0
29   81  81   92  79   78       0
30   62  59   90  82   86       1
31   87  78   62  97   74       0
32   84  79   94  89   56       1
33   61  80  100  69   52       1
34   83  55   88  53   86       2
35   68  50   59  97   55       3
36   90  54   51  52   52       4
37   50  79   70  91   80       1
38   57  86   87  58   75       2
39   90  70   88  60   74       0
40   76  99   57  87   54       2
41   54  64   54  78   50       3
42   54  95   80  90   88       1
43   73  93   77  52   80       1
44   64  89   98  95   66       0
45   60  90   83  87   86       0
46   66  93   98  71   71       0
47   75  75   77  94   50       1
48   66  57   93  71   72       1
49   85  54   52  73   75       2
50   83  94   77  67   78       0

In [31]:
def cal3(s):
    return pd.Series([s.min(),s.max(),s.std()],index=['最低分','最高分','標準差'])
scores_df3 = scores_df.apply(cal3)

In [32]:
display(scores_df)
scores_df3

科目   國文  英文   數學  地理   歷史
學號
1    90  53   97  67   86
2    67  69   64  89   86
3    50  99   97  88   92
4    67  55   78  56   55
5    60  97   68  89  100
6    63  96   90  81   76
7    97  80  100  89   83
8    99  72   53  92   56
9    58  59   93  54   54
10   63  58   87  65   51
11   55  98   95  93   52
12   60  95   99  95   75
13   63  82   81  91   60
14   90  54   59  89   92
15   97  69  100  88   90
16   98  75   95  94   97
17   70  97   58  99   54
18   79  88   75  89  100
19   89  87   95  56   78
20   76  78   93  60   57
21   53  58   95  57   62
22   71  73   66  54   64
23   82  63   79  91   60
24   50  81   61  67   86
25  100  69   66  65   96
26   95  58   71  96   69
27   79  68   81  93   63
28   93  90   73  87   83
29   81  81   92  79   78
30   62  59   90  82   86
31   87  78   62  97   74
32   84  79   94  89   56
33   61  80  100  69   52
34   83  55   88  53   86
35   68  50   59  97   55
36   90  54   51  52   52
37   50  79   70  91   80
38   57  86   87  58   75
39   90  70   88  60   74
40   76  99   57  87   54
41   54  64   54  78   50
42   54  95   80  90   88
43   73  93   77  52   80
44   64  89   98  95   66
45   60  90   83  87   86
46   66  93   98  71   71
47   75  75   77  94   50
48   66  57   93  71   72
49   85  54   52  73   75
50   83  94   77  67   78

科目           國文        英文          數學        地理          歷史
最低分   50.000000  50.00000   51.000000  52.00000   50.000000
最高分  100.000000  99.00000  100.000000  99.00000  100.000000
標準差   15.139636  15.35598   15.425714  15.35065   15.202376

In [33]:
#Combine both table
pd.concat([scores_df, scores_df3])

科目           國文        英文          數學        地理          歷史
1     90.000000  53.00000   97.000000  67.00000   86.000000
2     67.000000  69.00000   64.000000  89.00000   86.000000
3     50.000000  99.00000   97.000000  88.00000   92.000000
4     67.000000  55.00000   78.000000  56.00000   55.000000
5     60.000000  97.00000   68.000000  89.00000  100.000000
6     63.000000  96.00000   90.000000  81.00000   76.000000
7     97.000000  80.00000  100.000000  89.00000   83.000000
8     99.000000  72.00000   53.000000  92.00000   56.000000
9     58.000000  59.00000   93.000000  54.00000   54.000000
10    63.000000  58.00000   87.000000  65.00000   51.000000
11    55.000000  98.00000   95.000000  93.00000   52.000000
12    60.000000  95.00000   99.000000  95.00000   75.000000
13    63.000000  82.00000   81.000000  91.00000   60.000000
14    90.000000  54.00000   59.000000  89.00000   92.000000
15    97.000000  69.00000  100.000000  88.00000   90.000000
16    98.000000  75.00000   95.000000  94.00000   97.000000
17    70.000000  97.00000   58.000000  99.00000   54.000000
18    79.000000  88.00000   75.000000  89.00000  100.000000
19    89.000000  87.00000   95.000000  56.00000   78.000000
20    76.000000  78.00000   93.000000  60.00000   57.000000
21    53.000000  58.00000   95.000000  57.00000   62.000000
22    71.000000  73.00000   66.000000  54.00000   64.000000
23    82.000000  63.00000   79.000000  91.00000   60.000000
24    50.000000  81.00000   61.000000  67.00000   86.000000
25   100.000000  69.00000   66.000000  65.00000   96.000000
26    95.000000  58.00000   71.000000  96.00000   69.000000
27    79.000000  68.00000   81.000000  93.00000   63.000000
28    93.000000  90.00000   73.000000  87.00000   83.000000
29    81.000000  81.00000   92.000000  79.00000   78.000000
30    62.000000  59.00000   90.000000  82.00000   86.000000
31    87.000000  78.00000   62.000000  97.00000   74.000000
32    84.000000  79.00000   94.000000  89.00000   56.000000
33    61.000000  80.00000  100.000000  69.00000   52.000000
34    83.000000  55.00000   88.000000  53.00000   86.000000
35    68.000000  50.00000   59.000000  97.00000   55.000000
36    90.000000  54.00000   51.000000  52.00000   52.000000
37    50.000000  79.00000   70.000000  91.00000   80.000000
38    57.000000  86.00000   87.000000  58.00000   75.000000
39    90.000000  70.00000   88.000000  60.00000   74.000000
40    76.000000  99.00000   57.000000  87.00000   54.000000
41    54.000000  64.00000   54.000000  78.00000   50.000000
42    54.000000  95.00000   80.000000  90.00000   88.000000
43    73.000000  93.00000   77.000000  52.00000   80.000000
44    64.000000  89.00000   98.000000  95.00000   66.000000
45    60.000000  90.00000   83.000000  87.00000   86.000000
46    66.000000  93.00000   98.000000  71.00000   71.000000
47    75.000000  75.00000   77.000000  94.00000   50.000000
48    66.000000  57.00000   93.000000  71.00000   72.000000
49    85.000000  54.00000   52.000000  73.00000   75.000000
50    83.000000  94.00000   77.000000  67.00000   78.000000
最低分   50.000000  50.00000   51.000000  52.00000   50.000000
最高分  100.000000  99.00000  100.000000  99.00000  100.000000
標準差   15.139636  15.35598   15.425714  15.35065   15.202376